[package]
name = "rust-bip352"
version = "0.1.0"
edition = "2021"

[dependencies]
bech32 = "0.11.0"
bitcoin = "0.32.5"
secp256k1 = { git = "https://github.com/nymius/rust-secp256k1", branch = "bip352-silentpayments-module-REBASED", version = "0.30.0" }
